"""edit reset password column

Revision ID: 4b337a3700a3
Revises: 12290f04bd38
Create Date: 2022-05-19 11:14:34.419541

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b337a3700a3'
down_revision = '12290f04bd38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'reset_password',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'reset_password',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
